### ISSUE TITLE
Cannot find module or its corresponding type declarations.

### ISSUE THREAD

**Issue by rtritto** [brillout/json-serializer#13]
```console
error TS2307: Cannot find module '@brillout/json-serializer/parse' or its corresponding type declarations.

error TS2307: Cannot find module '@brillout/json-serializer/stringify' or its corresponding type declarations.
```

Related: https://github.com/vikejs/vike/pull/1955#issuecomment-2462074898

**Comment by brillout** [comment]
I think adding `types` to `package.json#exports` fixes it &mdash; to be tested. PR welcome.

**Comment by rtritto** [comment]
An alternative should be:
1. refactor definition files
    - `/dist/cjs/parse.d.ts`
    - `/dist/cjs/stringify.d.ts`
    - `/dist/cjs/types.d.ts`
    - `/dist/esm/parse.d.ts`
    - `/dist/esm/stringify.d.ts`
    - `/dist/esm/types.d.ts`
    
    to
    - `/dist/parse.d.ts`
    - `/dist/stringify.d.ts`
    - `/dist/types.d.ts`

2. create an `/dist/index.d.ts` that exports all of them
3. add `"types": "./dist/index.d.ts"` in `package.json#exports`

**Comment by brillout** [comment]
We cannot remove the CJS build.

> I think adding `types` to `package.json#exports` fixes it — to be tested. PR welcome.

Let's do this instead. @rtritto up for a PR?

**Comment by rtritto** [comment]
Opened #14
