### ISSUE TITLE
Cannot serialize functions

### ISSUE THREAD

**Issue by uifox** [brillout/json-serializer#4]
My vite-ssr app uses vuex on the server side. The vuex store contains state with error objects that have properties pointing to functions. These errors are thrown by APIs and I can't control their structure.

State serialization fails due to the function properties and I see similar errors in the log:

```
1:21:48 PM [vite] Error when evaluating SSR module /renderer/_default.page.server.ts:
Error: Cannot serialize `foo` because it is a function. Serializer: https://github.com/brillout/json-s
    at Object.replacer (/node_modules/@brillout/json-s/dist/esm/stringify.js:22:19)
    at JSON.stringify (<anonymous>)
    at serializer (/node_modules/@brillout/json-s/dist/esm/stringify.js:11:38)
    at Module.stringify (/node_modules/@brillout/json-s/dist/esm/stringify.js:12:12)
    at /home/node/renderer/_default.page.server.ts:18:100
```

Would it be possible to make the serialization safe the way that it never throws an error?

**Comment by brillout** [comment]
Functions cannot be serialized. For SSR apps, you have to make sure that your initial state is serializable.
